#############################################################################
# Makefile for building: yuv_noise
# Generated by qmake (2.01a) (Qt 4.7.0) on: Tue Jul 26 19:27:13 2011
# Project:  yuv_noise.pro
# Template: app
# Command: /opt/qtsdk-2010.05/qt/bin/qmake -spec /opt/qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile yuv_noise.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2010.05/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2010.05/qt/include/QtCore -I/opt/qtsdk-2010.05/qt/include/QtGui -I/opt/qtsdk-2010.05/qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk-2010.05/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2010.05/qt/lib -lQtGui -L/opt/qtsdk-2010.05/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2010.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Console.cpp \
		ConvertYuvToRgb.cpp \
		main.cpp \
		mainwindow.cpp \
		YUVImage.cpp moc_Console.cpp \
		moc_mainwindow.cpp
OBJECTS       = Console.o \
		ConvertYuvToRgb.o \
		main.o \
		mainwindow.o \
		YUVImage.o \
		moc_Console.o \
		moc_mainwindow.o
DIST          = /opt/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		yuv_noise.pro
QMAKE_TARGET  = yuv_noise
DESTDIR       = 
TARGET        = yuv_noise

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: yuv_noise.pro  /opt/qtsdk-2010.05/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2010.05/qt/lib/libQtGui.prl \
		/opt/qtsdk-2010.05/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile yuv_noise.pro
/opt/qtsdk-2010.05/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2010.05/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2010.05/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2010.05/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri:
/opt/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2010.05/qt/lib/libQtGui.prl:
/opt/qtsdk-2010.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile yuv_noise.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/yuv_noise1.0.0 || $(MKDIR) .tmp/yuv_noise1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/yuv_noise1.0.0/ && $(COPY_FILE) --parents Console.h ConvertYuvToRgb.h mainwindow.h types.h YUVImage.h .tmp/yuv_noise1.0.0/ && $(COPY_FILE) --parents Console.cpp ConvertYuvToRgb.cpp main.cpp mainwindow.cpp YUVImage.cpp .tmp/yuv_noise1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/yuv_noise1.0.0/ && (cd `dirname .tmp/yuv_noise1.0.0` && $(TAR) yuv_noise1.0.0.tar yuv_noise1.0.0 && $(COMPRESS) yuv_noise1.0.0.tar) && $(MOVE) `dirname .tmp/yuv_noise1.0.0`/yuv_noise1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/yuv_noise1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Console.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Console.cpp moc_mainwindow.cpp
moc_Console.cpp: Console.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) Console.h -o moc_Console.cpp

moc_mainwindow.cpp: types.h \
		YUVImage.h \
		mainwindow.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/qtsdk-2010.05/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Console.o: Console.cpp Console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Console.o Console.cpp

ConvertYuvToRgb.o: ConvertYuvToRgb.cpp ConvertYuvToRgb.h \
		types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConvertYuvToRgb.o ConvertYuvToRgb.cpp

main.o: main.cpp mainwindow.h \
		types.h \
		YUVImage.h \
		Console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		types.h \
		YUVImage.h \
		ui_mainwindow.h \
		Console.h \
		ConvertYuvToRgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

YUVImage.o: YUVImage.cpp YUVImage.h \
		types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o YUVImage.o YUVImage.cpp

moc_Console.o: moc_Console.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Console.o moc_Console.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

